version: '3.1'
services:

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-stats
    ports:
      - "9091:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=develop
      - POSTGRES_PASSWORD=postgres

  ewm-db:
    image: postgres:14-alpine
    container_name: postgres-main
    ports:
      - "8081:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=develop
      - POSTGRES_PASSWORD=postgres

  stats-server:
    build: stats-server/.
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=develop
      - SPRING_DATASOURCE_PASSWORD=postgres

  ewm-service:
    build: ewm-service/.
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=develop
      - SPRING_DATASOURCE_PASSWORD=postgres
      - STATS-SERVER_URL=http://stats-server:9090
