DROP TABLE IF EXISTS users, categories, events, participation_requests, compilations, events_compilations, reactions;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories(
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(256) NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT uq_category_name UNIQUE (category_name)
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation TEXT NOT NULL,
    category_id INT NOT NULL,
    confirmed_count BIGINT DEFAULT 0,
    created_date TIMESTAMP NOT NULL,
    description TEXT,
    event_date TIMESTAMP NOT NULL,
    initiator_id BIGINT NOT NULL,
    location_lat FLOAT NOT NULL,
    location_lon FLOAT NOT NULL,
    paid BOOLEAN DEFAULT FALSE,
    participant_limit INT DEFAULT 0,
    published_date TIMESTAMP,
    request_moderation BOOLEAN DEFAULT TRUE,
    title VARCHAR(120) NOT NULL,
    state VARCHAR(16),
    views BIGINT,

    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT fk_category_id FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT fk_initiator_id FOREIGN KEY (initiator_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requester_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    created_date TIMESTAMP NOT NULL,
    status VARCHAR(16) NOT NULL,
    CONSTRAINT pk_participation_request PRIMARY KEY (id),
    CONSTRAINT fk_requester_id FOREIGN KEY (requester_id) REFERENCES users(id),
    CONSTRAINT fk_request_event_id FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN DEFAULT FALSE,
    title VARCHAR(126) NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (id),
    CONSTRAINT uq_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS events_compilations (
    event_id BIGINT NOT NULL,
    compilation_id BIGINT NOT NULL,
    CONSTRAINT fk_event_id FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_compilation FOREIGN KEY (compilation_id) REFERENCES compilations(id)
);

CREATE TABLE IF NOT EXISTS reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    reaction INT NOT NULL,
    CONSTRAINT pk_estimation PRIMARY KEY (id),
    CONSTRAINT fk_grade_event_id FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_grade_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);


